// @flow
export const currencySymbols = {
	USD: '\u0024',
	EUR: '\u20AC',
	AUD: '\u0024',
	BGN: '\u043b\u0432',
	BRL: '\u0052\u0024',
	CAD: '\u0024',
	CHF: '\u0043\u0048\u0046',
	CNY: '\u00a5',
	CYP: '\u00A3',
	CZK: '\u004b\u010d',
	DKK: '\u006b\u0072',
	EEK: '\u006b\u0072',
	GBP: '\u00A3',
	HKD: '\u0024',
	HRK: '\u006b\u006e',
	HUF: '\u0046\u0074',
	IDR: '\u0052\u0070',
	ILS: '\u20aa',
	INR: '\u20b9',
	ISK: 'Íkr',
	JPY: '\u00a5',
	KRW: '\u20a9',
	LTL: 'Lt',
	LVL: 'Ls',
	MXN: '\u0024',
	MYR: '\u0052\u0042',
	MTL: '₤',
	NOK: '\u006b\u0072',
	NZD: '\u0024',
	PHP: '\u20b1',
	PLN: '\u007a\u0142',
	ROL: 'leu',
	RON: '\u006c\u0065\u0069',
	RUB: '\u20bd',
	SEK: '\u006b\u0072',
	SIT: 'tolar',
	SKK: 'Sk',
	SGD: '\u0024',
	THB: '\u0e3f',
	TRL: '\u20ba',
	TRY: '\u20ba',
	ZAR: '\u0052'
};

export const humanReadableCurrencies = {
	USD: 'U.S. dollar',
	EUR: 'Euro',
	AUD: 'Australian dollar',
	BGN: 'Bulgarian lev',
	BRL: 'Brazilian real',
	CAD: 'Canadian dollar',
	CHF: 'Swiss franc',
	CNY: 'Chinese yuan',
	CYP: 'Cypriot pound',
	CZK: 'Czech koruna',
	DKK: 'Danish krone',
	EEK: 'Estonian kroon',
	GBP: 'Pound sterling',
	HKD: 'Hong Kong dollar',
	HRK: 'Croatian kuna',
	HUF: 'Hungarian forint',
	IDR: 'Indonesian rupiah',
	ILS: 'Israeli new shekel',
	INR: 'Indian rupee',
	ISK: 'Icelandic króna',
	JPY: 'Japanese yen',
	KRW: 'South Korean won',
	LTL: 'Lithuanian litas',
	LVL: 'Latvian lats',
	MXN: 'Mexican peso',
	MYR: 'Malaysian ringgit',
	MTL: 'Maltese lira',
	NOK: 'Norwegian krone',
	NZD: 'New Zealand dollar',
	PHP: 'Philippine peso',
	PLN: 'Polish złoty',
	ROL: 'Romanian leu',
	RON: 'Romanian new leu',
	RUB: 'Russian ruble',
	SEK: 'Swedish krona',
	SIT: 'Slovenian tolar',
	SKK: 'Slovak Koruna',
	SGD: 'Singapore dollar',
	THB: 'Thai baht',
	TRL: 'Turkish (old) lira',
	TRY: 'Turkish lira',
	ZAR: 'South African rand'
};
